experiment:
  val_copy_train: True
  exp_type: cunet
  accelerator: cuda
  
  model:
    activation: leaky_relu
    depth: 3
    start_channels: 128
    dilation: 2.0
    up_sample: False
    maxpool: False

  dataset_train:
    input_size: 256, 256
    data_dir: ./data/train
    delta: 45
    sample_interval: 1
    max_angle: 180
    normalize: True
    encoder_depth: 3
  
  dataset_val:
    sample_interval: 5
    data_dir: ./data/val
  
  trainer:
    use_validation: True
    lr: 0.0005
    loss: custom_mse
    early_stopping_patience: Null # No early stopping
    batch_size_train: 12 # Let trainer figure out max batch_size
    batch_size_val: Null # Let trainer figure out max batch_size
    epochs: 5
    viz_sample_frequency: 4
    vis_sample_num: 4
